version: 2.1

orbs:
  node: circleci/node@4.7

node_modules_cache_key: &node_modules_cache_key node_modules-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.lock" }}

default_config: &default_config
  docker:
    - image: cimg/node:16.10
#  environment:
#    JEST_WORKERS: 2

commands:
  save_node_modules:
    steps:
      - save_cache:
          key: *node_modules_cache_key
          paths:
            - ./node_modules
  restore_node_modules:
    steps:
      - restore_cache:
          key: *node_modules_cache_key
  ensure_ahead_of_main:
    steps:
      - run:
          name: Ensure branch is ahead of main
          command: |
            git fetch origin main;
            if ! git merge-base --is-ancestor origin/main HEAD;
            then
            printf '\n\n ** Your branch must be ahead of main to deploy **\n\n';
            exit 1;
            fi

jobs:
  install_dependencies:
    <<: *default_config
    steps:
      - checkout
      - restore_node_modules
      - node/install-packages:
          pkg-manager: npm
      - save_node_modules
  lint:
    <<: *default_config
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: Lint
          command: npm run lint
  check_types:
    <<: *default_config
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: Check types
          command: echo "Check types will be implemented!"
  unit_tests:
    <<: *default_config
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: Run unit tests
          command: echo "Run unit tests will be implemented!"
  integration_tests:
    <<: *default_config
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: Run integration tests
          command: echo "Run integration tests will be implemented!"
  acceptance_tests:
    <<: *default_config
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: Run acceptance tests
          command: echo "Run integration tests will be implemented!"
  test:
    <<: *default_config
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: Run tests
          command: npm run test
  build:
    <<: *default_config
    steps:
      - checkout
      - restore_node_modules
      - run:
          name: Build
          command: npm run build
  deploy:
    <<: *default_config
    steps:
      - checkout
      - restore_node_modules
      - add_ssh_keys
      - run: 
          name: Installing OS packages
          command: sudo apt-get -y update && sudo apt install rsync
      - run:
          name: deploy.sh
          command: sh .circleci/deploy.sh
      - run:
          name: Smoke tests 
          command: echo "smoke tests will be implemented!"

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - install_dependencies:
          context: dev
      - lint:
          requires:
            - install_dependencies
      - check_types:
          requires:
            - install_dependencies
      - unit_tests:
          requires:
            - install_dependencies
      - integration_tests:
          context: dev
          requires:
            - install_dependencies
      - acceptance_tests:
          context: dev
          requires:
            - install_dependencies
      - approve_dev:
          type: approval
          requires:
            - install_dependencies
      - deploy:
          name: deploy_dev
          context: dev
          requires:
            - approve_dev
      - approve_prod:
          type: approval
          requires:
            - approve_dev
      - deploy:
          name: deploy_prod
          context: prod
          requires:
            - approve_prod